// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7a3eavC512Y28XEgbLGGdF5tOwrfZ8E',
    appId: '1:811727000444:web:7407a633ad1a0f444c4af9',
    messagingSenderId: '811727000444',
    projectId: 'financialtracker-f6b53',
    authDomain: 'financialtracker-f6b53.firebaseapp.com',
    databaseURL: 'https://financialtracker-f6b53-default-rtdb.firebaseio.com',
    storageBucket: 'financialtracker-f6b53.firebasestorage.app',
    measurementId: 'G-YKQFYB2N2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATToncKjQ1dHvyoLBv8Y7rx7sQDHHXqCI',
    appId: '1:811727000444:android:6ff3a6e26d73b0154c4af9',
    messagingSenderId: '811727000444',
    projectId: 'financialtracker-f6b53',
    databaseURL: 'https://financialtracker-f6b53-default-rtdb.firebaseio.com',
    storageBucket: 'financialtracker-f6b53.firebasestorage.app',
  );
}
